development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: colors_everywhere
  pool: 5
  username: ken.grimm
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: colors_everwhere_test
  pool: 5
  username: ken.grimm
  password:
